name: Run Update Delivery Data From NSE

on:
  schedule:
    - cron: '30 14 * * *'   # run every Friday 8pm IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas requests pytz

    - name: Run update script
      run: python FillMissingDeliveryDataFromNSE.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto-update DeliveryDataFromNSE: $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
